mode: "dev"

database:
  mysql:
    addr: "localhost:3306"
    user: "root"
    password: "root123"
    db_name: "moonick"
jwt:
  secret: "foobar"
  access_expires_in: "2h"
  refresh_expires_in: "72h"
r2:
  bucket_name: "bucket_name"
  account_id: "account_id"
  access_key_id: "access_key_id"
  access_key_secret: "access_key_secret"
  public_base_url: "https://pub-c986c455c9884a098d2751147be48ba8.r2.dev/"
